# Generated by Django 3.2.7 on 2022-08-03 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=200, null=True)),
                ('reg_name', models.CharField(max_length=200, null=True)),
                ('tin', models.IntegerField(null=True)),
                ('bldg', models.CharField(max_length=40, null=True)),
                ('brgy', models.CharField(max_length=40, null=True)),
                ('prov', models.CharField(max_length=40, null=True)),
                ('zip_code', models.CharField(max_length=4, null=True)),
                ('telephone', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('manager', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=200, null=True)),
                ('pos', models.CharField(max_length=40, null=True)),
                ('tel', models.IntegerField()),
                ('fax_num', models.IntegerField()),
                ('email_add', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('tin_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule1020.info')),
            ],
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_eco', models.CharField(max_length=200, null=True)),
                ('prod', models.CharField(max_length=200, null=True)),
                ('leg_org', models.CharField(max_length=15, null=True)),
                ('eco_org', models.CharField(max_length=15, null=True)),
                ('tot_emp', models.IntegerField()),
                ('male', models.IntegerField(null=True)),
                ('female', models.IntegerField(null=True)),
                ('alien', models.IntegerField()),
                ('reg', models.IntegerField(null=True)),
                ('non_reg', models.IntegerField(null=True)),
                ('bel_15', models.IntegerField()),
                ('above_15', models.IntegerField()),
                ('labor_union', models.CharField(max_length=200)),
                ('subcon', models.CharField(max_length=200)),
                ('subcon_emp', models.CharField(max_length=200)),
                ('tin_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule1020.info')),
            ],
        ),
    ]
