# Generated by Django 3.2.7 on 2022-08-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0003_alter_info_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Emp',
        ),
    ]
