# Generated by Django 3.2.7 on 2022-08-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0005_emp_mun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='brgy',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='bus_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='fax',
            new_name='fax_number',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='mun',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='prov',
            new_name='provine',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='reg_name',
            new_name='registered_name',
        ),
    ]
