# Generated by Django 3.2.7 on 2022-08-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0006_auto_20220812_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='bldg',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='provine',
            new_name='province',
        ),
    ]
