# Generated by Django 3.2.7 on 2022-08-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0008_auto_20220812_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='tin_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rule1020.emp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='tin',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
