# Generated by Django 3.2.7 on 2022-08-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0009_auto_20220812_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='tin_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule1020.emp'),
        ),
    ]
