# Generated by Django 3.2.7 on 2022-08-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0011_auto_20220812_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economic',
            name='tin_fk',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='tin_rep',
        ),
        migrations.DeleteModel(
            name='Economic',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
