# Generated by Django 3.2.7 on 2022-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0012_auto_20220815_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='above_15',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='alien',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='below_15',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='economic_organization',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='email_add',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='female',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='labor_union',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='legal_organization',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='main_economic_activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='major_products',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='male',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='non_regular',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='regular',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='representative_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='telephone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='total_employment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='total_number_of_subcontactors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='total_number_of_subcontracted_employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='fax_number',
            field=models.IntegerField(null=True),
        ),
    ]
