# Generated by Django 3.2.7 on 2022-08-31 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule1020', '0015_rename_municipality_barangay_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='above_15',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='alien',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='below_15',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='economic_organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='fax_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='labor_union',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='legal_organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='major_products',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_employment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_number_of_subcontactors',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_number_of_subcontracted_employees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='User_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('head', models.CharField(max_length=200, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule1020.province')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
