# Generated by Django 3.2.7 on 2022-08-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0016_auto_20220831_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_office',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
