# Generated by Django 3.2.7 on 2022-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0017_user_office_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='above_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='alien',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='below_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='fax_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='labor_union',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_number_of_subcontactors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_number_of_subcontracted_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
