# Generated by Django 3.2.7 on 2022-09-06 08:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0018_auto_20220831_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='cert_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_encoded',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_printed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='date_release',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
