# Generated by Django 3.2.7 on 2022-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0019_auto_20220906_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='date_encoded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='date_printed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='date_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='date_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
