# Generated by Django 3.2.7 on 2022-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0020_auto_20220906_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='date_encoded',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='date_registered',
        ),
        migrations.AlterField(
            model_name='emp',
            name='cert_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
