# Generated by Django 3.2.7 on 2022-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0021_auto_20220915_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='date_encoded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
