# Generated by Django 3.2.7 on 2022-09-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0022_auto_20220915_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='date_encoded',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='date_printed',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='date_release',
        ),
    ]
