# Generated by Django 3.2.7 on 2022-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule1020', '0023_auto_20220916_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='date_encoded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_printed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='date_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
